---
- name: Provision Ghost server
  become: true
  hosts: all
  vars:
    nodejs_version: 16
    site_name: maheshrjl.com

  tasks:
    - name: Update all packages
      ansible.builtin.apt:
        upgrade: true
        update_cache: true

    - name: Install NGINX & MySQL Server
      ansible.builtin.apt:
        name:
          - nginx
          - mysql-server
        state: present

    - name: Configure UFW rules for Nginx
      ansible.builtin.command: sudo ufw allow 'Nginx Full'

    - name: Install the gpg key for nodejs LTS
      ansible.builtin.apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Install the nodejs LTS repos
      ansible.builtin.apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: true

    - name: Install Node.js
      ansible.builtin.apt:
        name: nodejs
        state: present

    - name: Install Ghost-CLI
      community.general.npm:
        name: ghost-cli@latest
        global: true

    - name: Check version of installed dependencies
      ansible.builtin.command: "{{ item }}"
      loop:
        - node -v
        - npm -v
        - ghost -v
        - mysql --version
        - nginx -v
      register: version
      changed_when: false

    # - name: Print version of installed dependencies
    #   ansible.builtin.debug:
    #     msg: "{{ item.stdout }}"
    #   loop: "{{ version.results }}"

    - name: Create a ghost directory
      ansible.builtin.file:
        path: "/var/www/{{ site_name }}"
        state: directory
        mode: 0755
        owner: root

    - name: Prompt user for ghost install
      ansible.builtin.debug:
        msg: "Please run ghost install in /var/www/{{ site_name }} to complete the installation"
